### ISSUE TITLE
Pathing Question

### ISSUE THREAD

**Issue by streatim** [stephanieleary/coral-a11y-cleanup-2024#1]
The basic issue I ran into involved the resources and organizations modules using $_SERVER['DOCUMENT_ROOT'].'/coral/'... as their paths (though I believe this was done more widely?). As I see it, there's two potential problems with this change (though I'm not sure how widespread each would be) -

1. For the first, if CORAL has been installed in a deeper subdirectory of a library's webserver, it might not be under $_SERVER['DOCUMENT_ROOT'].'/coral/'. In [our current installation instructions](https://github.com/coral-erm/coral/wiki/Installing-CORAL), we invite users to consider installation in a subfolder in step 3, so if we keep this change we'll want to be sure that gets updated and notify the community.

2. This one's Dearborn-specific at the least and is caused by me not reading the README files (I used the installation instructions we provide outside of the Readme) - we git cloned the repo without the project folder so that our users could just go straight to the domain and not deal with the subdirectory (and we wouldn't have to mess with rewrites or anything). Looking at the README files, I do see now that they all reference that the "files are intended to be copied into the /coral/ directory on your web server.", so this may just be a situation where we have to change our local setup. However, the old pathing worked and my worry would be that we weren't the only institution that did that. 

I do think this is a situation where we (the steering committee) need to take a look at our installation instructions; if we keep with the assumption that everything is sitting in a /coral/ directory, I'd want to spell that out in Step 3. And, in all honesty, we should update the instructions since they're referencing 3.0 and not any of the 2020+ versions. 

I wonder if using the $coralPath variable rather than a $_SERVER['DOCUMENT_ROOT'] would be a better idea, at the least to address the potential of subdirectories being used. 

Sorry for dropping a comment rather than a direct fix! Once I figured out what was what and made local changes the UI is looking fantastic and I can't wait for us to implement it here!

**Comment by stephanieleary** [comment]
Fixed via PR #9.
