### ISSUE TITLE
(Idea) - Add Color Mode Toggle to Main Menu

### ISSUE THREAD

**Issue by streatim** [stephanieleary/coral-a11y-cleanup-2024#10]
Absolutely not an issue, just an idea. 

Staff here love the color mode toggle, but suggested that it would have been nice to toggle it at the main menu rather than wait until they get into a module. After thinking about it, I was thinking that this would also be an excellent opportunity to describe what the button indicates with a label (rather than just relying on the mouseover text). I've added a pull request that adds the button code to the index.php file and puts it above the "Choose Language" dropdown, but this could absolutely be rejected if there's any reason to do so.

**Comment by stephanieleary** [comment]
This is included in v0.1.0-alpha2. Thanks, @streatim !
