### ISSUE TITLE
Choose Language Dropdown not retained

### ISSUE THREAD

**Issue by streatim** [stephanieleary/coral-a11y-cleanup-2024#12]
I haven't been able to look deeply enough to confirm the issue at play, but we documented an issue where selecting a language from the dropdown menu does not appear to be "sticking" when navigating between modules and pages. Whenever a new page or module is selected, the language will revert to whatever it was read as when the user first entered the site. 

I tried adding checks to see if the $("#lang").change() function was firing (in js/common.js) but couldn't seem to get them to register, though that may have been due to my own amateur-ness.

**Comment by stephanieleary** [comment]
Fixed in beta1!
