### ISSUE TITLE
Several Issues with Cost History Tables

### ISSUE THREAD

**Issue by LibrarianMike** [stephanieleary/coral-a11y-cleanup-2024#13]
I found several issues with the Cost History Table for a resource:

1) Tax included and Final cost values no longer auto populate based on Tax Excluded and tax rate values.

2) New rows can't be added to the Cost History table for a resource (the add button doesn't seem to work)

3) Submitting incorrectly formatted dates wipe out the entire cost history table for a resource (this is an issue in the production release as well)

**Comment by stephanieleary** [comment]
The first two issues are fixed in v0.1.0-alpha2. The disappearing cost history is a much larger issue that will need to be addressed separately; see [coral-erm/coral/issues/707#issuecomment-2529682678](https://github.com/coral-erm/coral/issues/707#issuecomment-2529682678)
