### ISSUE TITLE
Resource Module Display Issues

### ISSUE THREAD

**Issue by LibrarianMike** [stephanieleary/coral-a11y-cleanup-2024#14]
I've noticed that different parts of the resource module handle notes differently. These differences made some notes hard to read/understand. Notes on the Product tab function as one would expect:

![Screenshot--Resources Norw](https://github.com/user-attachments/assets/ac9c7968-703c-42ba-ac83-dd5d20aa7c0f)

In this tab, notes display as one expects--in a easily readable table.

However, notes under the Access tab are less readable:
![Screenshot--Access Details Notes](https://github.com/user-attachments/assets/8c04d36c-ceeb-4a11-83fb-3a6f40160e30)

The note content appears above (and seemingly separate from) the note details table below the note content.

Also, the error message for an issue with note input covers more lines than necessary (the error generated when I tried to submit the note with no text, not when I input the text present in the screenshot.)
![Screenshot-Note error](https://github.com/user-attachments/assets/e2b55d7e-2937-48e3-a7de-74466177703a)

**Comment by stephanieleary** [comment]
This is fixed in v0.1.0-alpha2
