### ISSUE TITLE
Resource/Organization Contacts list is less readable in the Accessibility Branch

### ISSUE THREAD

**Issue by LibrarianMike** [stephanieleary/coral-a11y-cleanup-2024#15]
The new method for displaying resource and organization contacts is less readable to the human eye than the production method.

**Accessibility Branch Display**
![Screenshot-- Resources Contact Info](https://github.com/user-attachments/assets/8f0d59b3-3fc7-4868-83d7-0010420faf33)

**Production 2024.10 Display**
![Screenshot Resources Contact Info (Production)](https://github.com/user-attachments/assets/42e18bc7-35ae-47f5-8680-fdf5df9f61e5)

I understand that the gradient background that makes the Production list easier to read/skim is an accessibility no-no. However, I think a good solution would be to a) separate the Role information adjacent to the contact name into it's own grid row, b) make the contact name the grid structural equivalent of a heading and c) increase the spacing between listed contacts.

**Comment by stephanieleary** [comment]
This is fixed in v0.1.0-alpha2. Thanks for pointing out the discrepancy!

**Comment by LibrarianMike** [comment]
![Screenshot (8)](https://github.com/user-attachments/assets/a65744eb-331a-4add-bdd0-0eea0d62a79b)

Looking at the Inspector, the div element enclosing those values may be causing the issue. Chome is setting display to "display: block;"
