### ISSUE TITLE
Management Module: Red highlighting is misapplied in several instances

### ISSUE THREAD

**Issue by LibrarianMike** [stephanieleary/coral-a11y-cleanup-2024#17]
1) When a title of a file is entered, a red bar appears under the text field, with no explanatory text.

2) The message that a file was successfully attached to a management record is given a red highlight (green would make more sense since the notification is positive, not negative.

![Screenshot-Adding Document Management Module](https://github.com/user-attachments/assets/05bc4a25-e938-4c1c-abe8-95fb2489c084)

**Comment by stephanieleary** [comment]
This is fixed in v0.1.0-alpha2
