### ISSUE TITLE
Duplicate CORAL project Logos

### ISSUE THREAD

**Issue by LibrarianMike** [stephanieleary/coral-a11y-cleanup-2024#2]
![Duplicate Logos](https://github.com/user-attachments/assets/783c420d-5e74-4850-a4f8-ecf06e70d41f)

My test branch has duplicate logos in the page header. It looks like both light and dark mode logos are rendered in the page.

**Comment by stephanieleary** [comment]
This should be fixed in v0.1.0-alpha2

**Comment by LibrarianMike** [comment]
In the most recent build, I have no coral logo present.
![Screenshot (4)](https://github.com/user-attachments/assets/b8182339-9966-46e3-b752-eab8ffb02b91)

**Comment by LibrarianMike** [comment]
Logo is appearing as expected now. Must've been a caching issue!
