### ISSUE TITLE
Resources Module: Clicking Links for Current and Archived Issues and Downtime Displays a "Data Action Not Set Up" Message

### ISSUE THREAD

**Issue by LibrarianMike** [stephanieleary/coral-a11y-cleanup-2024#20]
Clicking the links opens a window listing issues (or saying there aren't any) as expected, but upon closing the window, you see a "Data Action Not Set Up" message under the link. The message will appear/disappear with repeated clicks of the links.

![Data Action Not Set Up](https://github.com/user-attachments/assets/ff5c3e4a-3122-4b0e-98e8-3c504689bd72)

**Comment by stephanieleary** [comment]
@LibrarianMike can you let me know if this is still an issue in v0.1.0-alpha2? I believe it was another instance of the `count()` problem.

**Comment by LibrarianMike** [comment]
@stephanieleary Issue is still present

**Comment by stephanieleary** [comment]
Ah ha! Found it. This will be fixed in the next release.

**Comment by stephanieleary** [comment]
Fixed in beta1!
