### ISSUE TITLE
Usage Statistics: Report Options: More Spacing between Platform Name and Edit Link

### ISSUE THREAD

**Issue by LibrarianMike** [stephanieleary/coral-a11y-cleanup-2024#24]
Production branch has a slight space between the platform name and the edit link. Having the space is probably the better design choice

Production
![Screenshot (7)](https://github.com/user-attachments/assets/55b3be4d-1b5d-41cc-a428-81db0b47f800)

Accessibility
![Screenshot (6)](https://github.com/user-attachments/assets/4fee5ddc-292a-4baa-803a-b9fd511336a7)

**Comment by stephanieleary** [comment]
Fixed in beta1!
