### ISSUE TITLE
CSS for Adding Sushi Platform results in unreadable left hand menu

### ISSUE THREAD

**Issue by LibrarianMike** [stephanieleary/coral-a11y-cleanup-2024#3]
Here is the page as rendered when trying to editing a SUSHI platform:
![Sushi (Adding Platform)](https://github.com/user-attachments/assets/3b5a9f2f-95ea-4a49-9636-fabe5ef76ba3)

The background is white, the link text is also white. The text is only visible by hovering over the links

**Comment by stephanieleary** [comment]
This should be fixed in v0.1.0-alpha2
