### ISSUE TITLE
Side Nav links in Sushi platform pages are broken

### ISSUE THREAD

**Issue by LibrarianMike** [stephanieleary/coral-a11y-cleanup-2024#4]
The side menu links in the Sushi platform screen are broken resulting in page not found errors.

For example, trying to view the titles page for a Sushi platform page does the following:

![Sidebar link not found](https://github.com/user-attachments/assets/bbd0567c-3a35-4f43-8db1-e0dddac2f573)

The  Sidebar URL is: https://coral-wju-test.equinoxoli.org/coral/usage/platformID=54&showTab=titles

**Comment by stephanieleary** [comment]
This should be fixed in v0.1.0-alpha2
