### ISSUE TITLE
SUSHI platforms Content tables don't render

### ISSUE THREAD

**Issue by LibrarianMike** [stephanieleary/coral-a11y-cleanup-2024#6]
Here is what I see:
![Sushi Admin](https://github.com/user-attachments/assets/55f63bb8-67ea-42d8-8572-7ed68696db60)

I assume the content is supposed to render in a sane (i.e. non Russian nest doll) table. However, no tables/content are rendered.

**Comment by LibrarianMike** [comment]
Compare to Production (2024.10)
![Sushi Platforms (2024 10)](https://github.com/user-attachments/assets/0718f0fd-4363-4b17-a169-f91871bd16a6)

**Comment by stephanieleary** [comment]
This looks like another instance of [the `count()` bug](https://github.com/coral-erm/coral/issues/781). I've pushed a few updates to the branch this morning that should resolve this, but I haven't tagged them in a new release just yet.

**Comment by stephanieleary** [comment]
This should be fixed in v0.1.0-alpha2
